export const SERVICIOS = 'GET_SERVICES'
export const USUARIOS = 'GET_USERS'
export const BUSCAR = "BUSCAR_SERVICIO"
export const FILTERCAT = "FILTRAR_POR_CATEGORIA"
export const ORDERALPH = "ORDER_BY_ALPH"
export const ORDERRAT = "ORDER_BY_RATING"
export const RESETORDER = "RESET_ORDER"